spring:
  application:
    name: SERVICE-REGISTRY

server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false