spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes[0]:
        id: EMPLOYEE-SERVICE
        uri: lb://EMPLOYEE-SERVICE
        predicates[0]: Path=/api/employees/**
      routes[1]:
        id: DEPARTMENT-SERVICE
        uri: lb://DEPARTMENT-SERVICE
        predicates[0]: Path=/api/departments/**
      routes[2]:
        id: ORGANIZATION-SERVICE
        uri: lb://ORGANIZATION-SERVICE
        predicates[0]: Path=/api/organizations/**
      gateway:
        globals:
          corsConfigurations:
            '[/**]':
              allowedOrigins: "https://docs.spring.io"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE

  zipkin:
    base-url: http://127.0.0.1:9411/zipkin/

server:
  port: '9191'

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    defaultZone: http://localhost:8761/eureka/



