spring:
#  datasource:
#    username: root
#    url: jdbc:mysql://localhost:3306/employee_db
#    password: '41494899'
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#    hibernate:
#      ddl-auto: update

  application:
    name: EMPLOYEE-SERVICE
  config:
    import: optional:configserver:http://localhost:8888
  rabbitmq:
    host: localhost
    port: 5672
    usernames: guest
    password: guest
  zipkin:
    base-url: http://127.0.0.1:9411/zipkin/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 0.1
logging:
  pattern:
    level: '%5p[${spring.application.name}, %X{traceId:-}, %X{spanId:-}]'
#server:
#  port: '8081'



#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    defaultZone: http://localhost:8761/eureka/
