spring:
  application:
    name: ORGANIZATION-SERVICE
  config:
    import: optional:configserver:http://localhost:8888
  rabbitmq:
    host: localhost
    port: 5672
    usernames: guest
    password: guest
#  datasource:
#    url: jdbc:mysql://localhost:3306/organization_db
#    username: root
#    password: '41494899'
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#    hibernate:
#        ddl-auto: update
#server:
#  port: 8083
#
#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
