spring:
  datasource:
    url: jdbc:mysql://localhost:3306/organization_db
    username: root
    password: '41494899'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
        ddl-auto: update
server:
  port: 8083
